### ISSUE TITLE
undefined reference to usbCrc16Append

### ISSUE THREAD

**Issue by cipherswami** [Robotechnic/DigiKeyboardFr#2]
usbdrv.c:618

**Comment by A5H1Q** [comment]
same issue here.. ;(  (Arduinodroid app)  

![WhatsApp Image 2021-11-07 at 11 59 22 AM](https://user-images.githubusercontent.com/46376026/140635341-1c301598-5bb8-470c-8c26-5d785eaa50d5.jpeg)
(

**Comment by Robotechnic** [comment]
I'm sorry but there is no usbdrc.c int the lib. Are you sure that you have the right version of it?

**Comment by cipherswami** [comment]
You can find usbdrv.c in the original code.

**Comment by cipherswami** [comment]
For now, I found a turnaround solution,

/> Clear the app Data of ArduinoDriod
/> Start the ArduinoDriod and import the [Digikeyboard](https://github.com/name-is-cipher/DigiKeyboard) or DigikeyboardFr Library 
/> *Don't close the ArduinoDriod
/> Import the code
/> compile the code (it will successfully compile now)
/> Upload to Board.

*important, once you close and start the ArduinoDriod again you will see this linking error.

**Comment by A5H1Q** [comment]
> For now, I found a turnaround solution,
> 
> /> Clear the app Data of ArduinoDriod /> Start the ArduinoDriod and import the [Digikeyboard](https://github.com/name-is-cipher/DigiKeyboard) or DigikeyboardFr Library /> *Don't close the ArduinoDriod /> Import the code /> compile the code (it will successfully compile now) /> Upload to Board.
> 
> *important, once you close and start the ArduinoDriod again you will see this linking error.

Thanks for the library upload. 🙌 But I'm still getting that error. What's ur Arduinodroid app version? And do we have to clear all data or just the cache? I've cleared all data, but when trying to import the library, it says library already exists, so should i delete the Arduinodroid library folders or somthing?

**Comment by A5H1Q** [comment]
So I've tried this hack on another phone with the latest version of Arduinodroid (6.10) it works for the initial time. Like you said 🎉  and my phone's getting app not installed for app ver 6.10 :(

**Comment by A5H1Q** [comment]
@name-is-cipher Confirmed ur hack works, But it looks like the issue might be with Arduinodroid app itself, and if the source was on github, we could've opened an issue there.. which i think its not sadly 😔

**Comment by cipherswami** [comment]
Damn digistump, they didn't even respond to my community user account verification.

**Comment by A5H1Q** [comment]
@name-is-cipher Can I ask u a quick doubt? Wht's the difference between DigiKeyboard.print(F("...")) and DigiKeyboard.print("...") the docs/wiki aren't much helpful to me..

**Comment by cipherswami** [comment]
I'm not sure what extra alphabets are there in French, But you can find small changes like Fr. instead of $, etc

**Comment by Robotechnic** [comment]
F() is an arduino base function which convert char * to  __FlashStringHelper*
With that, the code will search the string into the ROM instead of the RAM
If you want [here](https://forum.arduino.cc/t/what-does-the-f-do-exactly/89384) is an arduino topic about that

**Comment by Emdad05** [comment]
Too many thanks 😊😊

**Comment by Emdad05** [comment]
> Too many thanks 😊😊

It perfectly works
