### ISSUE TITLE
ME GUSTO Q EXISTA ESTA LIBRERIA PERO..

### ISSUE THREAD

**Issue by Piero15** [Robotechnic/DigiKeyboardFr#3]
me gusto mucho esta libreria tiene muchas funciones extras como las de volumen pero no pude encontrar el teclado de blackspace el boton que se usa para eliminar lo escrito :( no soy muy bueno en esto pero para mi proyecto es indispensable :(

**Comment by Robotechnic** [comment]
I will help you but I have some issues with my computer, I will publish a new version of the lib before week end I think

**Comment by Robotechnic** [comment]
Fixed in release v1.0.1 0bc6a21078380bb873a68ed676a09bd01b5c13be
You can see delete key in action in the sentences example

**Comment by Piero15** [comment]
eres el mejor ♥
